---

stages:
  - build

build:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t quadeare/docker-dind-java .
    - docker push quadeare/docker-dind-java